BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
--  Core tenancy
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.organizations (
  organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT    NOT NULL,
  plan        TEXT    NOT NULL DEFAULT 'standard',
  status      TEXT    NOT NULL DEFAULT 'active',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.organization_site (
  organization_site_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL
    REFERENCES public.organizations(organization_id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  time_zone  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.units (
  unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL
    REFERENCES public.organizations(organization_id) ON DELETE CASCADE,
  site_id BIGINT
    REFERENCES public.organization_site(organization_site_id) ON DELETE SET NULL,
  name       TEXT NOT NULL,
  code       TEXT NOT NULL,
  time_zone  TEXT NOT NULL DEFAULT 'Asia/Bangkok',
  CONSTRAINT uq_units_org_code UNIQUE (organization_id, code)
);

-- Platform users (RBAC lives at app level; keep schema simple)
CREATE TABLE IF NOT EXISTS public.users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL
    REFERENCES public.organizations(organization_id) ON DELETE CASCADE,
  full_name     TEXT NOT NULL,
  nickname      TEXT,
  role          TEXT NOT NULL,               -- e.g., admin | planner | readonly
  password_hash TEXT NOT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────────────
--  Reference data for shifts and staff
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.shift_patterns (
  shift_pattern_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id BIGINT NOT NULL
    REFERENCES public.units(unit_id) ON DELETE CASCADE,
  name        TEXT NOT NULL,                 -- Morning / Evening / Night
  start_time  TIME NOT NULL,
  end_time    TIME NOT NULL,
  is_night    BOOLEAN NOT NULL DEFAULT FALSE,
  required_skills JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS ix_shift_patterns_unit_night
  ON public.shift_patterns(unit_id, is_night);

CREATE TABLE IF NOT EXISTS public.staffs (
  staff_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id BIGINT NOT NULL
    REFERENCES public.units(unit_id) ON DELETE CASCADE,
  code             TEXT NOT NULL,            -- e.g., N01, AGT-12
  full_name        TEXT NOT NULL,
  nickname         TEXT,
  role             TEXT,                     -- optional; can normalize later
  skills           TEXT[] NOT NULL DEFAULT '{}'::text[],
  contract_type    TEXT,
  max_weekly_hours INT,
  enabled          BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_staffs_unit_code UNIQUE (unit_id, code)
);

-- ─────────────────────────────────────────────────────────────────────────────
--  Planning inputs (coverage, availability, preferences)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.coverage_requirement (
  coverage_requirement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id BIGINT NOT NULL
    REFERENCES public.units(unit_id) ON DELETE CASCADE,
  day      DATE NOT NULL,
  shift_id BIGINT NOT NULL
    REFERENCES public.shift_patterns(shift_pattern_id) ON DELETE RESTRICT,
  required_count INT NOT NULL CHECK (required_count >= 0),
  required_skill JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT uq_covreq_unit_day_shift UNIQUE (unit_id, day, shift_id)
);
CREATE INDEX IF NOT EXISTS ix_covreq_unit_day
  ON public.coverage_requirement(unit_id, day);

CREATE TABLE IF NOT EXISTS public.availability (
  availability_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL
    REFERENCES public.staffs(staff_id) ON DELETE CASCADE,
  day      DATE NOT NULL,
  shift_id BIGINT NOT NULL
    REFERENCES public.shift_patterns(shift_pattern_id) ON DELETE RESTRICT,
  value INT NOT NULL CHECK (value IN (0,1)),
  CONSTRAINT uq_availability_staff_day_shift UNIQUE (staff_id, day, shift_id)
);

CREATE TABLE IF NOT EXISTS public.preferences (
  preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL
    REFERENCES public.staffs(staff_id) ON DELETE CASCADE,
  day      DATE NOT NULL,
  shift_id BIGINT NOT NULL
    REFERENCES public.shift_patterns(shift_pattern_id) ON DELETE RESTRICT,
  penalty INT NOT NULL DEFAULT 0 CHECK (penalty >= 0),
  CONSTRAINT uq_preferences_staff_day_shift UNIQUE (staff_id, day, shift_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
--  Policy/config, scenarios, runs, and outputs
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.policy_sets (
  policy_set_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id BIGINT NOT NULL
    REFERENCES public.units(unit_id) ON DELETE CASCADE,
  name       TEXT NOT NULL,                  -- e.g., "ER Policy"
  version    TEXT NOT NULL,                  -- e.g., "v1"
  weights    JSONB NOT NULL,                 -- mirrors Weights model
  hard_rules JSONB NOT NULL,                 -- hard caps, sequence bans, etc.
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_policy_unit_name_version UNIQUE (unit_id, name, version)
);

CREATE TABLE IF NOT EXISTS public.scenarios (
  scenario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id BIGINT NOT NULL
    REFERENCES public.units(unit_id) ON DELETE CASCADE,
  source     TEXT NOT NULL,                  -- web | chatbot | csv
  input_hash TEXT NOT NULL,                  -- SHA256 of normalized payload
  payload    JSONB NOT NULL,                 -- exact SolveRequest snapshot
  status     TEXT NOT NULL DEFAULT 'ready',
  created_by BIGINT
    REFERENCES public.users(user_id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_scenarios_unit_hash UNIQUE (unit_id, input_hash)
);
CREATE INDEX IF NOT EXISTS ix_scenarios_unit_created
  ON public.scenarios(unit_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.solver_runs (
  solver_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scenario_id BIGINT NOT NULL
    REFERENCES public.scenarios(scenario_id) ON DELETE CASCADE,
  policy_set_id BIGINT NOT NULL
    REFERENCES public.policy_sets(policy_set_id) ON DELETE RESTRICT,
  status TEXT NOT NULL,                       -- queued|running|succeeded|failed
  seed   INT,
  workers INT,
  wall_time_sec DOUBLE PRECISION,
  code_version TEXT,
  logs_url TEXT,
  started_at  TIMESTAMPTZ,
  finished_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_solver_runs_scn_status
  ON public.solver_runs(scenario_id, status);
CREATE INDEX IF NOT EXISTS ix_solver_runs_finished
  ON public.solver_runs(finished_at DESC);

CREATE TABLE IF NOT EXISTS public.assignments (
  assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  solver_run_id BIGINT NOT NULL
    REFERENCES public.solver_runs(solver_run_id) ON DELETE CASCADE,
  day      DATE NOT NULL,
  shift_id BIGINT NOT NULL
    REFERENCES public.shift_patterns(shift_pattern_id) ON DELETE RESTRICT,
  staff_id BIGINT NOT NULL
    REFERENCES public.staffs(staff_id) ON DELETE RESTRICT,
  is_overtime BOOLEAN NOT NULL DEFAULT FALSE,
  source      TEXT NOT NULL DEFAULT 'MODEL',  -- MODEL | POSTFILL
  CONSTRAINT uq_assignments_unique_row UNIQUE (solver_run_id, day, shift_id, staff_id)
);
CREATE INDEX IF NOT EXISTS ix_assignments_run
  ON public.assignments(solver_run_id);
CREATE INDEX IF NOT EXISTS ix_assignments_day_shift
  ON public.assignments(day, shift_id);

-- Optional KPI table (attach metrics per run)
CREATE TABLE IF NOT EXISTS public.kpi (
  solver_run_id BIGINT PRIMARY KEY
    REFERENCES public.solver_runs(solver_run_id) ON DELETE CASCADE,
  avg_satisfaction INT NOT NULL CHECK (avg_satisfaction BETWEEN 0 AND 100),
  understaff_total INT NOT NULL,
  overtime_total   INT NOT NULL,
  night_violations INT NOT NULL,
  senior_coverage_ok BOOLEAN NOT NULL
);

COMMIT;
